blog_v2/blog/urls.py
from django.urls import path 
from . import views

app_name = 'blog'

urlpatterns = [
	# path('',views.post_list,name = 'post_list'),
	path('',views.PostListView.as_view(),name='post_list'),
	path('detail/<int:year>/<int:month>/<int:day>/<slug:post>',views.post_detail,name = 'post_detail'),
	path('<int:post_id>/share/',views.post_share, name='post_share'),
]

blog_v2/blog_v2/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('',include('blog.urls',namespace = 'blog')),
    path('admin/', admin.site.urls),
]

blog_v2/blog/models.py
from django.db import models
from django.utils import timezone 
from django.contrib.auth.models import User 
from django.urls import reverse

class PublishedManager(models.Manager):
	def get_queryset(self):
		return super().get_queryset().filter(status="published")


class Post(models.Model):
	STATIC_CHOISES = (('draft','Draft'),('published','Published'))
	title   = models.CharField('Заголовок статьи', max_length=50)
	slug    = models.SlugField(max_length = 250,unique_for_date='publish')
	author  = models.ForeignKey(User,on_delete = models.CASCADE,related_name='blog_posts')
	body    = models.TextField()
	publish = models.DateTimeField(default=timezone.now)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now = True)
	status  = models.CharField(max_length=10,choices=STATIC_CHOISES,default='draft')

	objects  = models.Manager()
	published = PublishedManager()

	def get_absolute_url(self):
		return reverse('blog:post_detail',args=[self.publish.year,self.publish.month,self.publish.day,self.slug])

	class Meta:
		ordering     = ('-publish',)
		verbose_name = "Пост"
		verbose_name_plural = "Посты"
	def __str__(self):
		return self.title

class Comment(models.Model):
	post  = models.ForeignKey(Post, on_delete=models.CASCADE, related_name = 'comments')
	name  = models.CharField(max_length=80)
	email = models.EmailField()
	body = models.TextField()
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	active = models.BooleanField(default=True)

	class Meta:
		ordering = ('created',)
	def __str__(self):
		return 'Comment by {} on {}'.format(self.name, self.post)

blog_v2/blog/forms.py
from django import forms
from django.forms import fields
from .models import Comment

class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ('name','email','body')

class EmailPostForm(forms.Form):
	name  = forms.CharField(max_length = 25)
	email = forms.EmailField()
	to = forms.EmailField()
	comments = forms.CharField(required=False,widget=forms.Textarea)

blog_v2/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.utils.timezone import activate
from .models import Post, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger #Модули для создани пагинации
from django.views.generic import ListView
from .forms import EmailPostForm, CommentForm
from django.core.mail import send_mail

class PostListView(ListView):
	queryset = Post.published.all()
	context_object_name = 'posts'
	paginate_by = 3
	template_name = 'blog/post/list.html'
		
def post_list(request):
	objects_list = Post.published.all() 	 #Берем все записи из БД
	paginator    = Paginator(objects_list,2) #По 2 статьи на каждой странице
	page 		 = request.GET.get('page') 	 #берем GET параметр page 
	try:
		posts = paginator.page(page)
	except PageNotAnInteger:
		posts = paginator.page(1)
	except EmptyPage:
		posts = paginator.page(paginator.num_pages)
	return render(request,'blog/post/list.html',{'page':page,'posts':posts})

def post_detail(request,year,month,day,post):
	post = get_object_or_404(Post,slug = post,publish__year = year,publish__month=month,publish__day=day)
	comments = post.comments.filter(active = True)
	new_comment = None
	if request.method == "POST":
		comment_form = CommentForm(data=request.POST)
		if comment_form.is_valid():
			new_comment = comment_form.save(commit=True)
			new_comment.post = post
			new_comment.save()
	else:
		comment_form = CommentForm()
	return render(request,'blog/post/detail.html',{'post':post,'comment_form':comment_form,'comments':comments,'new_comment': new_comment})

def post_share(request,post_id):
	post = get_object_or_404(Post,id=post_id,status = 'published')
	sent = False
	if(request.method == 'POST'):
		form = EmailPostForm(request.POST)
		if form.is_valid():
			cd = form.cleaned_data
			# Отправка электронной почты 
			post_url = request.build_absolute_uri(post.get_absolute_url())
			subject = '{} ({}) recomends you reading {}'.format(cd['name'],cd['email'],post.title)
			message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(post.title,post_url,cd['name'],cd['comments'])
			send_mail(subject,message,'admin@email.ru',[cd['to']])
			sent = True
	else:
		form = EmailPostForm()
	return render(request, 'blog/post/share.html',{'post':post,'form': form,'sent':sent})

blog_v2/blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title> {% block title %} {% endblock %} </title>
	<link rel="stylesheet" href="{% static 'css/blog.css' %}">
</head>
<body>
	<div id="content">
		{% block content %}{% endblock %}
	</div>
	<div id="sidebar">
		<h2>My blog</h2>
		<p>This is my blog</p>
	</div>
</body>
</html>

blog_v2/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% block title %}{{post.title}}{% endblock %}

{% block content %}
	<h1> {{ post.title }} </h1>
	<p class="date">Publish {{post.publish}} by {{post.auhtor}}</p>
	{{ post.body|linebreaks}}
	<p>
		<a href='{% url "blog:post_share" post.id %}'>Share post</a>
	</p>
{% endblock %}

blog_v2/blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% block title %} My Blog {% endblock %}

{% block content %}
	{% for post in posts %}
			<h2>
				<a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
			</h2>
			<p class="date">Publish {{post.publish}} by {{post.auhtor}}</p>
			{{ post.body|truncatewords:20|linebreaks}}
			<hr>
	{% endfor %}

	{% include "pagination.html" with page=page_obj %}

{% endblock %}

blog_v2/blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}
    Share post
{% endblock %}


{% block content %}
    
    {% if sent %}
        <h1>Email sent successfuly</h1>
        <p>"{{ post.title }}" was successfuly sent to {{ form.clean_data.to }}</p>
    {% else %}
        <h1>Share "{{ post.title }}" by email</h1>
        <form action="." method="POST">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Send email">
        </form> 
    {% endif %}
        
{% endblock content %}

blog_v2/blog/templates/pagination.html
<div class="pagination">
	<span class="step-links">
		{% if page.has_previous  %}
			<a href="?page={{ page.previous_page_number }}">Previous</a>
		{% endif %}
		<span class="current">Page {{ page.number }} of {{ page.paginator.num_pages}}</span>
		{% if page.has_next %}
			<a href="?page={{ page.next_page_number }}">Next</a>
		{% endif %}
	</span>
</div>